export { default as App } from './App';
export * from './api/auth';
export { default as axios } from './api/axios';
export * from './components/SharedLayout';
export { default as Button } from './components/atoms/Button';
export { default as CanvasBackground } from './components/atoms/CanvasBackground';
export { default as GoogleButton } from './components/atoms/GoogleButton';
export { default as GalaxyParticles } from './components/molecules/GalaxyParticles';
export { default as HeaderBackground3D } from './components/molecules/HeaderBackground3D';
export { default as LogoWithText } from './components/molecules/LogoWithText';
export { default as MovieCard } from './components/molecules/MovieCard';
export * from './components/organisms/BackgroundParticles';
export { default as CategoriesGrid } from './components/organisms/CategoriesGrid';
export { default as Footer } from './components/organisms/Footer';
export { default as Header } from './components/organisms/Header';
export { default as HeaderUser } from './components/organisms/HeaderUser';
export { default as HeroWelcome } from './components/organisms/HeroWelcome';
export { default as MovieCarrousel } from './components/organisms/MovieCarrousel';
export { default as MovieTiltGroup } from './components/organisms/MovieTiltGroup';
export { default as PopularMovies } from './components/organisms/PopularMovies';
export { default as UpcomingSlider } from './components/organisms/UpcomingSlider';
export { default as UserProfileForm } from './components/organisms/UserProfileForm';
export { default as WelcomeContent } from './components/organisms/WelcomeContent';
export { default as Home } from './components/pages/Home';
export { default as Profile } from './components/pages/Profile';
export { default as WelcomePage } from './components/pages/WelcomePage';
export { default as Login } from './components/pages/auth/Login';
export { default as Register } from './components/pages/auth/Register';
export * from './firebase/config';
export * from './main';
export { default as AppRouter } from './routes/AppRouter';
export { default as PrivateRoute } from './routes/PrivateRoute';
export * from './store/authStore';
